Feature config file
Andrey-VU/RunVolunteerBotPavshino pull request #1
Opened 2023-10-06 16:59 UTC by Sintsoft

Набросал скелет

2023-10-06 17:58 UTC, Andrey-VU reviewed
Олег, спасибо за оперативность! 
Сижу под впечатлением от скорости реализации проекта. Нервно думаю, сколько времени бы ушло без этого на пробы и ошибки)  
Ощущение, что уже почти всё готово. Архитектура красивая, аккуратная. 
Всё компилируется.  
Там подсветил пару косметический ошибок. Поправь, пожалуйста.

2023-10-06 17:58 UTC, Andrey-VU commented on src/main/java/telegram/bot/adapter/TelegramBotStorage.java
> +    void delteParticipation(Participation participation);
в названии метода ошибка. 
delte вместо delete. В имплементации delete

2023-10-06 17:58 UTC, Andrey-VU commented on src/main/java/telegram/bot/adapter/google/TelegramBotStorageGoogleTableImpl.java
> +    public List<User> getPartisipansByDate(LocalDate date) {
предлагаю использовать название getParticipantsByDate

2023-10-06 17:58 UTC, Andrey-VU commented on src/main/java/telegram/bot/adapter/TelegramBotStorage.java
> +    List<User> getPartisipansByDate(LocalDate date);
предлагаю использовать название getParticipantsByDate

2023-10-06 18:44 UTC, Andrey-VU approved these changes

2023-10-07 06:43 UTC, noir74y requested changes

2023-10-07 06:43 UTC, noir74y commented on src/main/java/telegram/bot/model/User.java
кажется, поля этого класса тоже можно сделать private, как в Participation

2023-10-07 06:43 UTC, noir74y commented on src/main/java/telegram/bot/adapter/google/TelegramBotStorageGoogleTableImpl.java
кажется, поля этого класса тоже можно сделать private, как в Participation

2023-10-07 07:04 UTC, noir74y approved these changes

2023-10-07 07:47 UTC, merged